### ISSUE TITLE
TestNet.exe的源码在哪

### ISSUE THREAD

**Issue by vanhelsing18** [Tonyfy/LCNN_TRAIN#10]
tony大神，请问下有没有提供TestNet.exe的源码我想学习一下

**Comment by Tonyfy** [comment]
http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm
出处在这里，源码你看能不能找得到。

**Comment by vanhelsing18** [comment]
tony大神~厚着脸皮再来问下bbox.txt里1_001.jpg 65 178 78 191 后面的四个数字代表什么，我要换多张图片的话，这里该怎么写

**Comment by Tonyfy** [comment]
face location: left right top bottom.

**Comment by Tonyfy** [comment]
换图的话，要自己做一下face location.

**Comment by Why19970701** [comment]
想问一下这个MFC做界面的代码在哪里，想学习一下
