### ISSUE TITLE
 1.8 million  training iteration times, but the test accuracy is about 0.5, is that right?

### ISSUE THREAD

**Issue by iscas-lee** [Tonyfy/LCNN_TRAIN#11]
I0914 09:33:36.987599  6584 sgd_solver.cpp:106] Iteration 1851200, lr = 0.000174488
I0914 09:33:43.461599  6584 solver.cpp:228] Iteration 1851300, loss = 0.183091
I0914 09:33:43.461599  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:33:43.461599  6584 sgd_solver.cpp:106] Iteration 1851300, lr = 0.000174482
I0914 09:33:49.933599  6584 solver.cpp:228] Iteration 1851400, loss = 0.606006
I0914 09:33:49.933599  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:33:49.933599  6584 sgd_solver.cpp:106] Iteration 1851400, lr = 0.000174476
I0914 09:33:56.406599  6584 solver.cpp:228] Iteration 1851500, loss = 0.571156
I0914 09:33:56.406599  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:33:56.406599  6584 sgd_solver.cpp:106] Iteration 1851500, lr = 0.000174469
I0914 09:34:02.905799  6584 solver.cpp:228] Iteration 1851600, loss = 0.418948
I0914 09:34:02.905799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:34:02.905799  6584 sgd_solver.cpp:106] Iteration 1851600, lr = 0.000174463
I0914 09:34:09.381799  6584 solver.cpp:228] Iteration 1851700, loss = 0.0690969
I0914 09:34:09.381799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:34:09.381799  6584 sgd_solver.cpp:106] Iteration 1851700, lr = 0.000174456
I0914 09:34:15.836799  6584 solver.cpp:228] Iteration 1851800, loss = 0.274711
I0914 09:34:15.836799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:34:15.836799  6584 sgd_solver.cpp:106] Iteration 1851800, lr = 0.00017445
I0914 09:34:22.301800  6584 solver.cpp:228] Iteration 1851900, loss = 0.556112
I0914 09:34:22.301800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.75
I0914 09:34:22.301800  6584 sgd_solver.cpp:106] Iteration 1851900, lr = 0.000174444
I0914 09:34:28.700799  6584 solver.cpp:337] Iteration 1852000, Testing net (#0)
I0914 09:34:29.266799  6584 solver.cpp:391] Test loss: 3.77606
I0914 09:34:29.266799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.4675
I0914 09:34:29.294800  6584 solver.cpp:228] Iteration 1852000, loss = 0.070474
I0914 09:34:29.294800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:34:29.294800  6584 sgd_solver.cpp:106] Iteration 1852000, lr = 0.000174437
I0914 09:34:35.765799  6584 solver.cpp:228] Iteration 1852100, loss = 0.226924
I0914 09:34:35.765799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:34:35.765799  6584 sgd_solver.cpp:106] Iteration 1852100, lr = 0.000174431
I0914 09:34:42.221799  6584 solver.cpp:228] Iteration 1852200, loss = 0.648706
I0914 09:34:42.221799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.78125
I0914 09:34:42.221799  6584 sgd_solver.cpp:106] Iteration 1852200, lr = 0.000174425
I0914 09:34:48.687799  6584 solver.cpp:228] Iteration 1852300, loss = 0.377885
I0914 09:34:48.687799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:34:48.687799  6584 sgd_solver.cpp:106] Iteration 1852300, lr = 0.000174418
I0914 09:34:55.157799  6584 solver.cpp:228] Iteration 1852400, loss = 0.530284
I0914 09:34:55.157799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:34:55.157799  6584 sgd_solver.cpp:106] Iteration 1852400, lr = 0.000174412
I0914 09:35:01.607800  6584 solver.cpp:228] Iteration 1852500, loss = 0.257938
I0914 09:35:01.607800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:35:01.607800  6584 sgd_solver.cpp:106] Iteration 1852500, lr = 0.000174405
I0914 09:35:08.076799  6584 solver.cpp:228] Iteration 1852600, loss = 0.27629
I0914 09:35:08.076799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:35:08.076799  6584 sgd_solver.cpp:106] Iteration 1852600, lr = 0.000174399
I0914 09:35:14.526799  6584 solver.cpp:228] Iteration 1852700, loss = 0.328374
I0914 09:35:14.526799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:35:14.526799  6584 sgd_solver.cpp:106] Iteration 1852700, lr = 0.000174393
I0914 09:35:20.991799  6584 solver.cpp:228] Iteration 1852800, loss = 0.405679
I0914 09:35:20.991799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:35:20.991799  6584 sgd_solver.cpp:106] Iteration 1852800, lr = 0.000174386
I0914 09:35:27.446799  6584 solver.cpp:228] Iteration 1852900, loss = 0.544654
I0914 09:35:27.446799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:35:27.446799  6584 sgd_solver.cpp:106] Iteration 1852900, lr = 0.00017438
I0914 09:35:33.837800  6584 solver.cpp:337] Iteration 1853000, Testing net (#0)
I0914 09:35:34.394799  6584 solver.cpp:391] Test loss: 3.56771
I0914 09:35:34.394799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.495
I0914 09:35:34.420799  6584 solver.cpp:228] Iteration 1853000, loss = 0.216011
I0914 09:35:34.420799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:35:34.420799  6584 sgd_solver.cpp:106] Iteration 1853000, lr = 0.000174374
I0914 09:35:40.890799  6584 solver.cpp:228] Iteration 1853100, loss = 0.318283
I0914 09:35:40.890799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:35:40.890799  6584 sgd_solver.cpp:106] Iteration 1853100, lr = 0.000174367
I0914 09:35:47.363800  6584 solver.cpp:228] Iteration 1853200, loss = 0.332405
I0914 09:35:47.363800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:35:47.363800  6584 sgd_solver.cpp:106] Iteration 1853200, lr = 0.000174361
I0914 09:35:53.817800  6584 solver.cpp:228] Iteration 1853300, loss = 0.436057
I0914 09:35:53.817800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:35:53.817800  6584 sgd_solver.cpp:106] Iteration 1853300, lr = 0.000174355
I0914 09:36:00.295799  6584 solver.cpp:228] Iteration 1853400, loss = 0.667568
I0914 09:36:00.295799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.78125
I0914 09:36:00.295799  6584 sgd_solver.cpp:106] Iteration 1853400, lr = 0.000174348
I0914 09:36:06.755800  6584 solver.cpp:228] Iteration 1853500, loss = 0.609652
I0914 09:36:06.755800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:36:06.755800  6584 sgd_solver.cpp:106] Iteration 1853500, lr = 0.000174342
I0914 09:36:13.220799  6584 solver.cpp:228] Iteration 1853600, loss = 0.749501
I0914 09:36:13.220799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.75
I0914 09:36:13.220799  6584 sgd_solver.cpp:106] Iteration 1853600, lr = 0.000174335
I0914 09:36:19.695799  6584 solver.cpp:228] Iteration 1853700, loss = 0.424909
I0914 09:36:19.695799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:36:19.695799  6584 sgd_solver.cpp:106] Iteration 1853700, lr = 0.000174329
I0914 09:36:26.165799  6584 solver.cpp:228] Iteration 1853800, loss = 0.249959
I0914 09:36:26.165799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:36:26.165799  6584 sgd_solver.cpp:106] Iteration 1853800, lr = 0.000174323
I0914 09:36:32.630800  6584 solver.cpp:228] Iteration 1853900, loss = 0.721237
I0914 09:36:32.630800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:36:32.630800  6584 sgd_solver.cpp:106] Iteration 1853900, lr = 0.000174316
I0914 09:36:39.029799  6584 solver.cpp:337] Iteration 1854000, Testing net (#0)
I0914 09:36:39.582799  6584 solver.cpp:391] Test loss: 3.77665
I0914 09:36:39.582799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.475
I0914 09:36:39.608799  6584 solver.cpp:228] Iteration 1854000, loss = 0.263935
I0914 09:36:39.608799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:36:39.608799  6584 sgd_solver.cpp:106] Iteration 1854000, lr = 0.00017431
I0914 09:36:46.059799  6584 solver.cpp:228] Iteration 1854100, loss = 0.150226
I0914 09:36:46.059799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:36:46.059799  6584 sgd_solver.cpp:106] Iteration 1854100, lr = 0.000174304
I0914 09:36:52.532799  6584 solver.cpp:228] Iteration 1854200, loss = 0.254497
I0914 09:36:52.532799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:36:52.532799  6584 sgd_solver.cpp:106] Iteration 1854200, lr = 0.000174297
I0914 09:36:58.983799  6584 solver.cpp:228] Iteration 1854300, loss = 0.240074
I0914 09:36:58.983799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:36:58.983799  6584 sgd_solver.cpp:106] Iteration 1854300, lr = 0.000174291
I0914 09:37:05.448799  6584 solver.cpp:228] Iteration 1854400, loss = 0.18402
I0914 09:37:05.448799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:37:05.448799  6584 sgd_solver.cpp:106] Iteration 1854400, lr = 0.000174285
I0914 09:37:11.923799  6584 solver.cpp:228] Iteration 1854500, loss = 0.585598
I0914 09:37:11.923799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:37:11.923799  6584 sgd_solver.cpp:106] Iteration 1854500, lr = 0.000174278
I0914 09:37:18.374799  6584 solver.cpp:228] Iteration 1854600, loss = 0.412825
I0914 09:37:18.374799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:37:18.374799  6584 sgd_solver.cpp:106] Iteration 1854600, lr = 0.000174272
I0914 09:37:24.826799  6584 solver.cpp:228] Iteration 1854700, loss = 0.324418
I0914 09:37:24.826799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:37:24.826799  6584 sgd_solver.cpp:106] Iteration 1854700, lr = 0.000174265
I0914 09:37:31.305799  6584 solver.cpp:228] Iteration 1854800, loss = 0.616231
I0914 09:37:31.305799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:37:31.305799  6584 sgd_solver.cpp:106] Iteration 1854800, lr = 0.000174259
I0914 09:37:37.772799  6584 solver.cpp:228] Iteration 1854900, loss = 0.485702
I0914 09:37:37.773799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:37:37.773799  6584 sgd_solver.cpp:106] Iteration 1854900, lr = 0.000174253
I0914 09:37:44.170799  6584 solver.cpp:337] Iteration 1855000, Testing net (#0)
I0914 09:37:44.726799  6584 solver.cpp:391] Test loss: 4.11952
I0914 09:37:44.726799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.475
I0914 09:37:44.751799  6584 solver.cpp:228] Iteration 1855000, loss = 0.106197
I0914 09:37:44.751799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:37:44.752799  6584 sgd_solver.cpp:106] Iteration 1855000, lr = 0.000174246
I0914 09:37:51.207799  6584 solver.cpp:228] Iteration 1855100, loss = 0.103739
I0914 09:37:51.207799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:37:51.207799  6584 sgd_solver.cpp:106] Iteration 1855100, lr = 0.00017424
I0914 09:37:57.676800  6584 solver.cpp:228] Iteration 1855200, loss = 0.678847
I0914 09:37:57.676800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:37:57.676800  6584 sgd_solver.cpp:106] Iteration 1855200, lr = 0.000174234
I0914 09:38:04.143800  6584 solver.cpp:228] Iteration 1855300, loss = 0.241907
I0914 09:38:04.143800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:38:04.143800  6584 sgd_solver.cpp:106] Iteration 1855300, lr = 0.000174227
I0914 09:38:10.615799  6584 solver.cpp:228] Iteration 1855400, loss = 0.528937
I0914 09:38:10.615799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:38:10.615799  6584 sgd_solver.cpp:106] Iteration 1855400, lr = 0.000174221
I0914 09:38:17.080799  6584 solver.cpp:228] Iteration 1855500, loss = 0.739377
I0914 09:38:17.081799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.75
I0914 09:38:17.081799  6584 sgd_solver.cpp:106] Iteration 1855500, lr = 0.000174215
I0914 09:38:23.549799  6584 solver.cpp:228] Iteration 1855600, loss = 0.544462
I0914 09:38:23.549799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:38:23.549799  6584 sgd_solver.cpp:106] Iteration 1855600, lr = 0.000174208
I0914 09:38:30.013799  6584 solver.cpp:228] Iteration 1855700, loss = 0.38861
I0914 09:38:30.013799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:38:30.013799  6584 sgd_solver.cpp:106] Iteration 1855700, lr = 0.000174202
I0914 09:38:36.480799  6584 solver.cpp:228] Iteration 1855800, loss = 0.261983
I0914 09:38:36.480799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:38:36.480799  6584 sgd_solver.cpp:106] Iteration 1855800, lr = 0.000174195
I0914 09:38:42.947799  6584 solver.cpp:228] Iteration 1855900, loss = 0.697443
I0914 09:38:42.947799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:38:42.947799  6584 sgd_solver.cpp:106] Iteration 1855900, lr = 0.000174189
I0914 09:38:49.350800  6584 solver.cpp:337] Iteration 1856000, Testing net (#0)
I0914 09:38:49.901799  6584 solver.cpp:391] Test loss: 4.44912
I0914 09:38:49.901799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.4525
I0914 09:38:49.928799  6584 solver.cpp:228] Iteration 1856000, loss = 0.167307
I0914 09:38:49.928799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:38:49.928799  6584 sgd_solver.cpp:106] Iteration 1856000, lr = 0.000174183
I0914 09:38:56.401799  6584 solver.cpp:228] Iteration 1856100, loss = 0.439052
I0914 09:38:56.401799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:38:56.401799  6584 sgd_solver.cpp:106] Iteration 1856100, lr = 0.000174176
I0914 09:39:02.875799  6584 solver.cpp:228] Iteration 1856200, loss = 0.285193
I0914 09:39:02.875799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:39:02.875799  6584 sgd_solver.cpp:106] Iteration 1856200, lr = 0.00017417
I0914 09:39:09.344799  6584 solver.cpp:228] Iteration 1856300, loss = 0.359473
I0914 09:39:09.344799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:39:09.344799  6584 sgd_solver.cpp:106] Iteration 1856300, lr = 0.000174164
I0914 09:39:15.805799  6584 solver.cpp:228] Iteration 1856400, loss = 0.800733
I0914 09:39:15.805799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:39:15.805799  6584 sgd_solver.cpp:106] Iteration 1856400, lr = 0.000174157
I0914 09:39:22.270799  6584 solver.cpp:228] Iteration 1856500, loss = 0.302216
I0914 09:39:22.270799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:39:22.270799  6584 sgd_solver.cpp:106] Iteration 1856500, lr = 0.000174151
I0914 09:39:28.735800  6584 solver.cpp:228] Iteration 1856600, loss = 0.154521
I0914 09:39:28.735800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:39:28.735800  6584 sgd_solver.cpp:106] Iteration 1856600, lr = 0.000174145
I0914 09:39:35.197799  6584 solver.cpp:228] Iteration 1856700, loss = 0.298379
I0914 09:39:35.197799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:39:35.197799  6584 sgd_solver.cpp:106] Iteration 1856700, lr = 0.000174138
I0914 09:39:41.658799  6584 solver.cpp:228] Iteration 1856800, loss = 0.166663
I0914 09:39:41.658799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:39:41.658799  6584 sgd_solver.cpp:106] Iteration 1856800, lr = 0.000174132
I0914 09:39:48.146800  6584 solver.cpp:228] Iteration 1856900, loss = 0.557385
I0914 09:39:48.146800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.78125
I0914 09:39:48.146800  6584 sgd_solver.cpp:106] Iteration 1856900, lr = 0.000174126
I0914 09:39:54.572799  6584 solver.cpp:337] Iteration 1857000, Testing net (#0)
I0914 09:39:55.127799  6584 solver.cpp:391] Test loss: 3.7937
I0914 09:39:55.127799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.4975
I0914 09:39:55.153800  6584 solver.cpp:228] Iteration 1857000, loss = 0.199672
I0914 09:39:55.153800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:39:55.153800  6584 sgd_solver.cpp:106] Iteration 1857000, lr = 0.000174119
I0914 09:40:01.610800  6584 solver.cpp:228] Iteration 1857100, loss = 0.240449
I0914 09:40:01.610800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:40:01.610800  6584 sgd_solver.cpp:106] Iteration 1857100, lr = 0.000174113
I0914 09:40:08.078799  6584 solver.cpp:228] Iteration 1857200, loss = 0.421281
I0914 09:40:08.078799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:40:08.078799  6584 sgd_solver.cpp:106] Iteration 1857200, lr = 0.000174107
I0914 09:40:14.538800  6584 solver.cpp:228] Iteration 1857300, loss = 0.238799
I0914 09:40:14.538800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.9375
I0914 09:40:14.538800  6584 sgd_solver.cpp:106] Iteration 1857300, lr = 0.0001741
I0914 09:40:21.005800  6584 solver.cpp:228] Iteration 1857400, loss = 0.228657
I0914 09:40:21.005800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:40:21.005800  6584 sgd_solver.cpp:106] Iteration 1857400, lr = 0.000174094
I0914 09:40:27.474799  6584 solver.cpp:228] Iteration 1857500, loss = 0.113201
I0914 09:40:27.474799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:40:27.474799  6584 sgd_solver.cpp:106] Iteration 1857500, lr = 0.000174088
I0914 09:40:33.143999  6584 solver.cpp:228] Iteration 1857600, loss = 0.909531
I0914 09:40:33.143999  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:40:33.143999  6584 sgd_solver.cpp:106] Iteration 1857600, lr = 0.000174081
I0914 09:40:39.610999  6584 solver.cpp:228] Iteration 1857700, loss = 0.380397
I0914 09:40:39.610999  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:40:39.610999  6584 sgd_solver.cpp:106] Iteration 1857700, lr = 0.000174075
I0914 09:40:46.124399  6584 solver.cpp:228] Iteration 1857800, loss = 0.316336
I0914 09:40:46.124399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:40:46.124399  6584 sgd_solver.cpp:106] Iteration 1857800, lr = 0.000174068
I0914 09:40:52.606400  6584 solver.cpp:228] Iteration 1857900, loss = 0.309551
I0914 09:40:52.606400  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:40:52.606400  6584 sgd_solver.cpp:106] Iteration 1857900, lr = 0.000174062
I0914 09:40:59.008399  6584 solver.cpp:337] Iteration 1858000, Testing net (#0)
I0914 09:40:59.561399  6584 solver.cpp:391] Test loss: 3.97371
I0914 09:40:59.561399  6584 solver.cpp:404]     Test net output #0: accuracy = 0.4875
I0914 09:40:59.584399  6584 solver.cpp:228] Iteration 1858000, loss = 0.382728
I0914 09:40:59.584399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:40:59.584399  6584 sgd_solver.cpp:106] Iteration 1858000, lr = 0.000174056
I0914 09:41:06.047399  6584 solver.cpp:228] Iteration 1858100, loss = 0.548754
I0914 09:41:06.047399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:41:06.047399  6584 sgd_solver.cpp:106] Iteration 1858100, lr = 0.000174049
I0914 09:41:12.507400  6584 solver.cpp:228] Iteration 1858200, loss = 0.478362
I0914 09:41:12.507400  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:41:12.507400  6584 sgd_solver.cpp:106] Iteration 1858200, lr = 0.000174043
I0914 09:41:18.969399  6584 solver.cpp:228] Iteration 1858300, loss = 0.332062
I0914 09:41:18.969399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:41:18.969399  6584 sgd_solver.cpp:106] Iteration 1858300, lr = 0.000174037
I0914 09:41:25.435400  6584 solver.cpp:228] Iteration 1858400, loss = 0.587138
I0914 09:41:25.436399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.8125
I0914 09:41:25.436399  6584 sgd_solver.cpp:106] Iteration 1858400, lr = 0.00017403
I0914 09:41:31.901399  6584 solver.cpp:228] Iteration 1858500, loss = 0.498611
I0914 09:41:31.901399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:41:31.901399  6584 sgd_solver.cpp:106] Iteration 1858500, lr = 0.000174024
I0914 09:41:38.362399  6584 solver.cpp:228] Iteration 1858600, loss = 0.496264
I0914 09:41:38.362399  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:41:38.362399  6584 sgd_solver.cpp:106] Iteration 1858600, lr = 0.000174018
I0914 09:41:44.857800  6584 solver.cpp:228] Iteration 1858700, loss = 0.509912
I0914 09:41:44.857800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:41:44.857800  6584 sgd_solver.cpp:106] Iteration 1858700, lr = 0.000174011
I0914 09:41:51.321799  6584 solver.cpp:228] Iteration 1858800, loss = 0.180461
I0914 09:41:51.321799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:41:51.321799  6584 sgd_solver.cpp:106] Iteration 1858800, lr = 0.000174005
I0914 09:41:57.799799  6584 solver.cpp:228] Iteration 1858900, loss = 0.65346
I0914 09:41:57.799799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:41:57.800799  6584 sgd_solver.cpp:106] Iteration 1858900, lr = 0.000173999
I0914 09:42:04.218799  6584 solver.cpp:337] Iteration 1859000, Testing net (#0)
I0914 09:42:04.775799  6584 solver.cpp:391] Test loss: 3.73394
I0914 09:42:04.776799  6584 solver.cpp:404]     Test net output #0: accuracy = 0.485
I0914 09:42:04.802799  6584 solver.cpp:228] Iteration 1859000, loss = 0.743077
I0914 09:42:04.802799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:42:04.802799  6584 sgd_solver.cpp:106] Iteration 1859000, lr = 0.000173992
I0914 09:42:11.266799  6584 solver.cpp:228] Iteration 1859100, loss = 0.386253
I0914 09:42:11.266799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:42:11.266799  6584 sgd_solver.cpp:106] Iteration 1859100, lr = 0.000173986
I0914 09:42:17.729799  6584 solver.cpp:228] Iteration 1859200, loss = 0.853737
I0914 09:42:17.729799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.78125
I0914 09:42:17.729799  6584 sgd_solver.cpp:106] Iteration 1859200, lr = 0.00017398
I0914 09:42:24.178799  6584 solver.cpp:228] Iteration 1859300, loss = 0.547904
I0914 09:42:24.178799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:42:24.178799  6584 sgd_solver.cpp:106] Iteration 1859300, lr = 0.000173973
I0914 09:42:30.638799  6584 solver.cpp:228] Iteration 1859400, loss = 0.492802
I0914 09:42:30.638799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.875
I0914 09:42:30.638799  6584 sgd_solver.cpp:106] Iteration 1859400, lr = 0.000173967
I0914 09:42:37.101799  6584 solver.cpp:228] Iteration 1859500, loss = 0.27371
I0914 09:42:37.101799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.96875
I0914 09:42:37.101799  6584 sgd_solver.cpp:106] Iteration 1859500, lr = 0.000173961
I0914 09:42:43.605799  6584 solver.cpp:228] Iteration 1859600, loss = 0.171972
I0914 09:42:43.605799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:42:43.605799  6584 sgd_solver.cpp:106] Iteration 1859600, lr = 0.000173954
I0914 09:42:50.068799  6584 solver.cpp:228] Iteration 1859700, loss = 0.533729
I0914 09:42:50.068799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:42:50.068799  6584 sgd_solver.cpp:106] Iteration 1859700, lr = 0.000173948
I0914 09:42:56.544800  6584 solver.cpp:228] Iteration 1859800, loss = 0.354224
I0914 09:42:56.544800  6584 solver.cpp:244]     Train net output #0: accuracy = 0.84375
I0914 09:42:56.544800  6584 sgd_solver.cpp:106] Iteration 1859800, lr = 0.000173942
I0914 09:43:03.003799  6584 solver.cpp:228] Iteration 1859900, loss = 0.262504
I0914 09:43:03.003799  6584 solver.cpp:244]     Train net output #0: accuracy = 0.90625
I0914 09:43:03.003799  6584 sgd_solver.cpp:106] Iteration 1859900, lr = 0.000173935

**Comment by Tonyfy** [comment]
@iscas-lee  looks on the right way ! and have you modified the training parameters?
 you can draw the curves using caffe tools in /caffe/tools/extra/..

**Comment by iscas-lee** [comment]
No. train data with your LCNN_solver.prototxt and LCNN_train_test.prototxt.
Test accuracy  vs. Iters picture  [http://118.145.8.43:8091/figure_1-1.png](http://118.145.8.43:8091/figure_1-1.png)
