### ISSUE TITLE
如何将人脸进行旋转和裁剪

### ISSUE THREAD

**Issue by breadbread1984** [Tonyfy/LCNN_TRAIN#15]
对人脸旋转剪裁是如何做的呢？是工程中的哪个文件呢？

**Comment by iscas-lee** [comment]
同问。
@Tonyfy  你的测试结果里面LFW的人脸不需要crop出来吗？ 我看你的结果里面人脸都是居中了的。

**Comment by Tonyfy** [comment]
@breadbread1984 @iscas-lee 
![image](https://cloud.githubusercontent.com/assets/11344664/21340991/fea36804-c6c4-11e6-8ae9-82ecc4d455f7.png)
根据面部关键点就可以啊。作者论文里面写了的。代码的话，就用opencv里面的warpaffine就可以。

**Comment by iscas-lee** [comment]
Thank you . Tongfy
