### ISSUE TITLE
Problem in evaluating on LFW

### ISSUE THREAD

**Issue by stoneyang** [Tonyfy/LCNN_TRAIN#16]
Hi, @Tonyfy 

Thanks for your cool code and it saved my life in replicating the work of Lightened CNN. 

I am a newbie in this field. Some problems make me confused when I tried to evaluated the trained caffemodel. :(

The script `lfw.py` generates the prediction and saved it to `predict.txt`. (Am I right?)

In your evaluation code [here](https://github.com/Tonyfy/LCNN_TRAIN/blob/master/accurate/lfw.py#L144-L146), it seems that some file's missing. Could you kindly provide the suggested `align_face.py`?  

Thanks in advance. 

Cheers.

**Comment by stoneyang** [comment]
I just feed the directory of LFW-deepfunneled to the option `'--lfw-feature'` and the script can run, but fails at [this line](https://github.com/Tonyfy/LCNN_TRAIN/blob/master/accurate/lfw.py#L49). Then I found the first two face patches do have different data lengths: `2196` for `Abel_Pacheco_0001.jpg`, `2457` for `Abel_Pacheco_0004.jpg`! 

How to solve this problem? ... 

P.S.: The dataset is downloaded from the official site and md5 checked.

**Comment by Tonyfy** [comment]
actually,if you want to evaluate the model, you should apply `face detect` and `face alignment` on LFW,then `get normalized cropped` face region(refer the source paper), then use the model to extract feature from this region.

all this step will be affect the accuracy of your own pipeline system. so your can experiment on any choice then to obtain the final result. as for face alignment, `warpaffine` in opencv should be easy to use.

best wishes.
