### ISSUE TITLE
demo.py对输入的人脸图像有什么要求么？

### ISSUE THREAD

**Issue by vanhelsing18** [Tonyfy/LCNN_TRAIN#17]
Tony大神 我随意拍了些照片没有经过处理 扔到demo.py尝试对比 发现精度特别差 ，我想问下 是不是要对输入的人脸图片经过些处理

**Comment by Tonyfy** [comment]
@vanhelsing18 输入需要是人脸图像，人脸是居中的，正方形。对pipeline的疑惑，可看原论文的预处理流程。

**Comment by vanhelsing18** [comment]
老哥 如何根据人脸标点的信息对人脸进行剪切和旋转 有什么大小和方向的标准么

**Comment by Tonyfy** [comment]
@vanhelsing18 [#issue15](https://github.com/Tonyfy/LCNN_TRAIN/issues/15)
