### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by peternara** [Tonyfy/LCNN_TRAIN#2]
I have my own experiments with the data and apply to your model(*.prototxt).
Composition of the difference is that dataset. (caffeType).
I made a lmdb using the caffe tool(using ~/caffe/build/tools/convert_imageset.bin).
first! made two file(train.txt, val.txt).
train.txt is format
[imagepath][blank][label]
example..
./0/0_20.jpg 0
./0/0_21.jpg 0
./0/0_22.jpg 0
./0/0_23.jpg 0
./0/0_24.jpg 0
./0/0_25.jpg 0
./0/0_26.jpg 0
./0/0_27.jpg 0
./0/0_28.jpg 0
...
./4900/4900_29.jpg 4900

val.txt is same.

and. image is grayscale and 144x144 size

finally i make train_lmdb/val_lmdb using tools'convert_imageset.bin

and.
I was created to the learning model by using train_lmdb/val_lmdb(adding LCNN_train_test.prototxt).
Using a model constructed softmax saw the results(about new image query).
But the results are very disappointed.

Originally, softmax ( fc2) results are bad is it?
or measurement distance(fc1) do you have to do(verification problem)?
or composition of the data wrong?

please, need your opinion.
I've had a few times did it, but it didn't get good results.

thank you.

**Comment by Tonyfy** [comment]
Firstly,the caffemodel trained by train_lmdb/val_lmdb should evaluate by verification problem(See LFW benchmark: http://vis-www.cs.umass.edu/lfw/pairs.txt ).For image query problem,the accurate maybe low,such as 40%-60% upon 10000 candidate person query. And the face feature is extracted from `eltwise_fc1` layer.
Secondly,for measurement distance on eltwise_fc1 feature,I just use cosine similarity which has good performance in LFW.
Finally,for you train data set, my train data set include 10575 person,494414 images.small train data set may cause bad caffemodel.

what else,have you clean you train data.the train image should only include face region which has been aligned and cropped.

wishes

**Comment by peternara** [comment]
thank you. i'll try it ^^

ps.

layer{
  name: "etlwise_fc1"
  type: "Eltwise"
  bottom: "slice_fc1_1"
  bottom: "slice_fc1_2"
  top: "eltwise_fc1"
  eltwise_param {
     operation: MAX
  }
}

name: "etlwise_fc1" --> eltwise_fc1 ???

This is a typo?

**Comment by Tonyfy** [comment]
@peternara , defintely typo! but doesn't matter.
:smile:
