### ISSUE TITLE
train light cnn

### ISSUE THREAD

**Issue by ctgushiwei** [Tonyfy/LCNN_TRAIN#20]
I'm training Light cnn now,my solver is:
base_lr: 0.001
momentum: 0.9
weight_decay: 0.0005
lr_policy: "step"
stepsize:500000
gamma:0.457305051927326

display: 100
max_iter: 4000000
snapshot: 40000
snapshot_prefix: "DeepFace_set003_net"

solver_mode: GPU

debug_info: false

clip_gradients: 150

I'm training light cnn with the clean list, after screening to get 79056 categories, about 4,920,000 images.But run 400,000 iteration loss is also 11.2?,Is this normal?do you have some advice?

I have another question in the layer of fc2,you have no param in this layer.

 param {
    lr_mult: 10
    decay_mult: 1
  }
  param {
    lr_mult: 20
    decay_mult: 0
  }

**Comment by Tonyfy** [comment]
@ctgushiwei 
I am not clear why you set these configuration,but lr's change step may be to high,and whether the batchsize or your inputdata is ok.it looks like that your net's loss doesn't change?

so,check the configuration careful and reasonable.the input data(I just use CASIA WebFace,which is bot same with your situation) might be in trouble too.

**Comment by ctgushiwei** [comment]
@Tonyfy  you mean you train the model just use CASIA WebFace?now Itrain use your solver and train_test_prototxt use 10575 categories, about 500,000 images.could you tell me how many  iterations your loss begin drop?
base_lr: 0.001
momentum: 0.9
weight_decay: 0.0005
lr_policy: "inv"
gamma: 0.00005
power: 0.75

**Comment by Tonyfy** [comment]
@ctgushiwei yes,just CASIA WebFace.once you have 79056 person,the fc2 layer' neural number  should set to 79056 as well.

During my training time,loss drop just in few epoches.

**Comment by liangsirrun** [comment]
hi,could you share your train log to me? I an not train the model as well as yours just use Webface about 10575 categories and about 500,000 images.

**Comment by ctgushiwei** [comment]
@liangsirrun the accuracy is 97.8%,not as well as the author
