### ISSUE TITLE
参数'--lfw-feature'是图片还是特征？

### ISSUE THREAD

**Issue by leeeeeeo** [Tonyfy/LCNN_TRAIN#22]
您好！
我在运行lfw.py的时候。
报错：IOError: [Errno 2] No such file or directory: '/media/data/liuhan/light_cnn/LCNN_TRAIN-master/accurate/lfw-deepfunneled-aligned/Abel_Pacheco/Abel_Pacheco_0001.data'
这是不是说明参数'--lfw-feature'这个文件夹里存的是图片的特征数据？
该怎么获得.data文件？
谢谢！

**Comment by Tonyfy** [comment]
是特征数据，使用训练的模型，提取lfw中人脸的特征存下来就可以了。

**Comment by leeeeeeo** [comment]
@Tonyfy 非常感谢您的回答。我理解您说的这个道理。可是如何保存成.data后缀的文件呢？不知道您是否方便提供一下提取特征的代码？非常感谢！！！

**Comment by Tonyfy** [comment]
@leeeeeeo 可以看看demo里面给出了使用python接口提特征的代码，至于后续在lfw上的验证，过程很繁琐，建议你弄清楚验证流程后自己做实验，特征以什么形式存储，不是重点。

**Comment by leeeeeeo** [comment]
@Tonyfy 
非常感谢!!!你要是和我在一个城市简直要请你吃饭了!
看了您的demo.py,使用您提供的caffemodel,EER达到了96.7%,可能是有些图片的处理不太一样导致的吧.
真的是非常感谢!!!

**Comment by Tonyfy** [comment]
@leeeeeeo 客气客气
