### ISSUE TITLE
OSError:

### ISSUE THREAD

**Issue by LXWDL** [Tonyfy/LCNN_TRAIN#24]
Hi,thanks for your codes. When I run the addLabeltopic.py,I encounter the following problems and don't know how to solver this error,can you help me? thank you very much!
Traceback (most recent call last):
  File "./tools/addLabeltopic.py", line 14, in <module>
    pic=os.listdir(folder)
OSError: [Errno 2] No such file or directory: '/home/dl/webface\\0031162'

**Comment by Tonyfy** [comment]
changing “path = '/X/X/X' to path = r'/X/X/X' "may solve the problem.
