### ISSUE TITLE
网络结构可以在此可视化

### ISSUE THREAD

**Issue by ghost** [Tonyfy/LCNN_TRAIN#25]
您好，我用http://ethereon.github.io/netscope/#/gist/c64671dc9359cc82c8baa02b1e1e5ec5， 后，显示Can't infer network data shapes. Can't infer output shape of the 'slice1' layer of type 'Slice'. Unsupported layer type: 'Slice'. 请问您那能绘制完整的网络结构吗

**Comment by Tonyfy** [comment]
@GengTianyu 有个warnning,还是能正常显示出来的

**Comment by ghost** [comment]
谢谢！！
