### ISSUE TITLE
可以对数据库进行对齐处理吗？

### ISSUE THREAD

**Issue by LXWDL** [Tonyfy/LCNN_TRAIN#26]
您好，请问LCNN可以对人脸数据库进行对齐处理吗？代码中的ReadMe中的内容有些看的不是很明白，如果您能写的更详细一点，或者写一些比较详细的使用步骤的博客，对我们这种小白将会有很大的帮助，感谢

**Comment by Tonyfy** [comment]
这个项目不能对人脸对齐，请参考face alignment的相关项目
