### ISSUE TITLE
灰度图像问题

### ISSUE THREAD

**Issue by cloudandcat** [Tonyfy/LCNN_TRAIN#27]
已经把自己的图片转成了灰度图但是在用您的模型fine-tune时，载入模型还是出现了这个错误：
Source param s hape is 96 1 5 5 (2400); target param shape is 96 3 5 5 (7200)
请问这是怎么回事呢

**Comment by honghuCode** [comment]
@cloudandcat 我在微调时也遇到了这个问题，请问是怎么解决的呢
