### ISSUE TITLE
请问tools工具的使用顺序？

### ISSUE THREAD

**Issue by morningsky** [Tonyfy/LCNN_TRAIN#3]
那个testNet.exe 我这无法运行

**Comment by Tonyfy** [comment]
@morningsky 是在cmd里面运行`TestNet.exe bbox.txt image Input result.bin`吗？看看code_point里面的readme,需要在image中准备好图片，在bbox.txt中设置好路径。

**Comment by getengqing** [comment]
@Tonyfy 你好，这里的bbox.txt是不是要我们自己首先准备好？

**Comment by Tonyfy** [comment]
@getengqing  对，bbox里面是指出每张图片中的人脸位置。

**Comment by tiankong1993** [comment]
博主您好，我好像在 github的face verification上见过您的提问的头像，请问可否提供一份对齐后的CASIA数据集呢？caffe入门者，想尝试着怎么去训练一个模型，感谢！best wish！
