### ISSUE TITLE
How did you get all of the bouding boxes of the whole casia-webface dataset?

### ISSUE THREAD

**Issue by msnqqer** [Tonyfy/LCNN_TRAIN#4]
The dataset contains many face images that is very difficult to be detected. Did you use your own face detection tool or some open-source?

**Comment by Tonyfy** [comment]
@msnqqer I use the fixed face bounding box of(65 178 78 191),after face alignment and face crop,you can evaluate the final face cropped.if you get good face region,what the bounding box is seem doesn't matter.

**Comment by msnqqer** [comment]
@Tonyfy  Thanks!
