### ISSUE TITLE
code_point文件夹里找不到processCASIA这个文件

### ISSUE THREAD

**Issue by vanhelsing18** [Tonyfy/LCNN_TRAIN#7]
博主，我刚接触这东西，现在不会运行，代码里面code_point这个路径里没有processCASIA这个文件夹请问如何解决，还想请教下博主，你的代码怎么实现检测两张图片是否同一个人QAQ

**Comment by Tonyfy** [comment]
@vanhelsing18 那个目录是申请到的CASIA数据集，自己建一个就行。这个LCNN网络可以提取人脸的特征，拿到两个人脸的特征后，使用一些距离度量的方式（如余弦距离度量）即可判断是否一个人。

**Comment by vanhelsing18** [comment]
提取人脸特征是指testNet.exe运行过后的得到的result.bin么 识别两个人的是否是同一个人是靠这个二进制文件么

**Comment by Tonyfy** [comment]
那个result只是face Alignment的结果，一系列的关键点坐标信息。不是人脸特征。

**Comment by vanhelsing18** [comment]
那用来区分人脸的人脸特征怎么用这个LCNN网络获得呢
